package com.couchbase.client.kotlin.codec

import com.couchbase.client.core.msg.kv.CodecFlags

/**
 * The encoded form of a KV value, with flags indicating the data type.
 */
public class Content(public val bytes: ByteArray, public val flags: Int) {
    public companion object {
        /**
         * A JSON document.
         */
        public fun json(value: ByteArray): Content = Content(value, CodecFlags.JSON_COMPAT_FLAGS)

        /**
         * A JSON document.
         */
        public fun json(value: String): Content = json(value.toByteArray())

        /**
         * Arbitrary binary content.
         */
        public fun binary(value: ByteArray): Content = Content(value, CodecFlags.BINARY_COMPAT_FLAGS)

        /**
         * Arbitrary textual content (UTF-8).
         */
        public fun string(value: String): Content = Content(value.toByteArray(), CodecFlags.STRING_COMPAT_FLAGS)

        /**
         * The serialized form of a Java object as generated by [java.io.ObjectOutputStream].
         */
        public fun serializedJavaObject(value: ByteArray): Content = Content(value, CodecFlags.SERIALIZED_COMPAT_FLAGS)
    }
}
