/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.sandbox

import com.couchbase.client.core.env.CoreEnvironment
import com.couchbase.client.core.env.PasswordAuthenticator
import com.couchbase.client.core.env.SeedNode
import com.couchbase.client.kotlin.Cluster
import com.couchbase.client.kotlin.ClusterOptions
import io.netty.buffer.ByteBuf
import io.netty.buffer.ByteBufUtil
import io.netty.buffer.Unpooled
import java.nio.charset.StandardCharsets.UTF_8

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}


fun main() {
    val auth = PasswordAuthenticator.create("Administrator", "password")

    val cluster = Cluster(CoreEnvironment.create(), auth, setOf(SeedNode.create("localhost")))

//    val cluster = Cluster.connect("localhost", "Administrator", "password")
    val collection = cluster.bucket("default").defaultCollection()

   // cluster.query("SELECT * from default")

    Cluster.connect("localhost", ClusterOptions(auth))
    println(collection.get("foo").content.toString(UTF_8))

}
